# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Vival Games
# Description of the Site
description: Wishlist On!
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Vival Games, Carvival, Devlog
# URL for the Image of custom Favicon
favicon-url: https://iili.io/J7FE6b4.md.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://iili.io/J7F7yoF.md.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hmtarhan@gmail.com

twitter_username: FoxyHasan
instagram_username: hasan.tarhan
linkedin_username: hasan-tarhan
github_username:  hasantarhan
youtube_channel_id: UCfMD_mioZ2WgP4hbxRnG6gA
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Hasan Tarhan
# URL for the Image of the Author
author-image: https://iili.io/J7F7P6b.md.jpg
# 60 Words About the Author
author-about:  Game developer, music lover, sci-fi geek, and a who likes to create immersive and fun experiences
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/hasantarhan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
